### ISSUE TITLE
speed prototyping cleanup

### ISSUE THREAD

**Issue by RyanDavidsonDev** [Do-Good-Games/NoCapstone2023#12]
the speedManager.cs is incredibly messy. While the original version was just a prototype, nearly all of the code included is obsolete, and what little remains relevant is very difficult to work with in the context of other features 
(for instance, speed can never be set or changed directly, it's always calculated by the private variables within it's black box)

**Comment by RyanDavidsonDev** [comment]
- [ ] refactor speed calculation to be direct adjustments to gameMan variable (rather than GM reading from black-box calculations)
- [ ] move boost over to speedMan
- [ ] remove speed when hit while charging

**Comment by Duckkk819** [comment]
sonic (he's fastt) 🫃
